const commandDatabase = {
  'Windows CMD': [
    'dir',
    'cd',
    'cls',
    'echo',
    'mkdir',
    'rmdir',
    'copy',
    'move',
    'del',
    'type',
    'ren',
    'ipconfig',
    'ping',
    'netstat',
    'tasklist',
    'taskkill',
  ],
  Linux: [
    'ls',
    'cd',
    'clear',
    'pwd',
    'mkdir',
    'rmdir',
    'cp',
    'mv',
    'rm',
    'cat',
    'touch',
    'chmod',
    'chown',
    'ifconfig',
    'ping',
    'netstat',
    'ps',
    'kill',
    'grep',
    'find',
    'man',
  ],
  Git: [
    'git init',
    'git clone',
    'git status',
    'git add',
    'git commit',
    'git push',
    'git pull',
    'git branch',
    'git checkout',
    'git merge',
    'git log',
    'git diff',
    'git remote',
    'git fetch',
    'git tag',
  ],
  Docker: [
    'docker run',
    'docker ps',
    'docker image',
    'docker build',
    'docker pull',
    'docker push',
    'docker stop',
    'docker rm',
    'docker rmi',
    'docker network',
    'docker volume',
    'docker-compose up',
    'docker-compose down',
    'docker logs',
    'docker exec',
    'docker container',
  ],
  Kubernetes: [
    'kubectl get pods',
    'kubectl get services',
    'kubectl get deployments',
    'kubectl apply -f',
    'kubectl delete',
    'kubectl describe',
    'kubectl logs',
    'kubectl exec',
    'kubectl config view',
    'kubectl cluster-info',
    'kubectl top node',
    'kubectl top pod',
    'kubectl rollout status',
    'kubectl scale',
    'helm install',
    'helm list',
  ],
};
